### ISSUE TITLE
Encrypt or obfuscate correct answers into JSON

### ISSUE THREAD

**Issue by carloscondit** [jdhitsolutions/PSQuizMaster#3]
It would be nice to have an option to encrypt or obfuscate the correct answers in the JSON file.

**Comment by jdhitsolutions** [comment]
I've added commands to handle this in v1.1.0. Update the module from the PowerShell gallery and let me know what you think.

**Comment by carloscondit** [comment]
It works. Thank you! But there is a problem. If the answer is given as a number, it remains unchanged.

**Comment by jdhitsolutions** [comment]
Hmmm. I hadn't thought about that. Let me see what I can come up with.

**Comment by jdhitsolutions** [comment]
I see the problem. Let me see how to fix it.

**Comment by carloscondit** [comment]
> I see the problem. Let me see how to fix it.

It was cool to have the wrong answers encrypted too. Knowing all the wrong answers makes it too easy to figure out the right one.

**Comment by jdhitsolutions** [comment]
I think I have this fixed. Update the module to version 1.2.0. I suggest starting with a plaintext quiz file and then run `Protect-PSQuizFile`.  Running `Unprotect-PSQuizFile` should also work.

**Comment by carloscondit** [comment]
> I think I have this fixed. Update the module to version 1.2.0. I suggest starting with a plaintext quiz file and then run `Protect-PSQuizFile`. Running `Unprotect-PSQuizFile` should also work.

Now it works with numbers. Thanks! Perhaps you might consider the option of defending all the answers? Knowing all the wrong answers makes it too easy to figure out the right one.

**Comment by jdhitsolutions** [comment]
I see your point. It wouldn't be that difficult to make that change.

**Comment by jdhitsolutions** [comment]
I finally got around to updating the module. Version 1.3.0 will now protect and unprotect distractors.

**Comment by carloscondit** [comment]
Thank you! I'll have to find the time and test the new version.
